name: Add chart via dispatch

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'repo'

      - run: |
          wget https://github.com/${{ github.event.client_payload.repository }}/releases/download/${{ github.event.client_payload.version }}/${{ github.event.client_payload.filename }} -o .repo/${{ github.event.client_payload.filename }}


      - name: Update index file for helm registry
        run: helm repo index repo

      - name: Set git info
        run: |
         git -C repo config user.email "${{ secrets.BOT_EMAIL }}"
         git -C repo config user.name "Bot"

      - name: git add changes
        run: git -C repo add .

      - name: git commit changes
        run: git -C repo commit -m "Updated the helm registry with file ${{ github.event.client_payload.filename }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: $
          branch: $
          
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}', '${{ github.event.client_payload.filename }}', '${{ github.event.client_payload.version }}'"
