name: Add chart via dispatch

on: [repository_dispatch]
env:
  BRANCH_NAME: 'gh-pages'
  REPO_PATH: 'repo'

jobs:
  add-chart:
    name: Add chart to helm registry.
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          path: ${{ env.REPO_PATH }}

      - name: "get chart tarball"
        run: |
          wget https://github.com/${{ github.event.client_payload.repository }}/releases/download/${{ github.event.client_payload.version }}/${{ github.event.client_payload.filename }} -O ./${{ env.REPO_PATH }}/${{ github.event.client_payload.filename }}

      - name: set git info
        run: |
         git -C ${{ env.REPO_PATH }} config user.email "bot@github.com"
         git -C ${{ env.REPO_PATH }} config user.name "Bot"

      - name: update index file for helm registry
        run: helm repo index ${{ env.REPO_PATH }}

      - name: git add changes
        run: git -C ${{ env.REPO_PATH }} add .

      - name: git commit changes
        run: git -C ${{ env.REPO_PATH }} commit -m "Updated the helm registry with file ${{ github.event.client_payload.filename }}"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ${{ env.REPO_PATH }}
          github_token: $
          branch: ${{ env.BRANCH_NAME }}
